org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
android.useAndroidX=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=true
